import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '/styles/globals.css'
import Navbar from '@/components/ui/navbar'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" >
      <body className={inter.className}>
        <Navbar />
        <div className='max-w-screen-lg	pt-5 m-auto'>
          {children}
        </div>
      </body>
    </html>
  )
}
